### ISSUE TITLE
Get loading-data?

### ISSUE THREAD

**Issue by utjduo** [naomiaro/waveform-playlist#13]
Hi! I'm loading some big and long files and it takes 10-15 seconds to load but all I see in the start is a white page and I don't know if it's loading or not.
I would wish to impant a loading-bar but I'll need to get the data of how much have bin loaded so far.
Is it possible to get this data some how?

Thanks!

**Comment by naomiaro** [comment]
Hi! Yes I would like to include this as well since other people have been asking for it. Currently the event emitter does emit some data about this, but it is not used anywhere in the project itself yet. You can check out the loaders

https://github.com/naomiaro/waveform-playlist/blob/master/src/track/loader/Loader.js

There is an event 'audiorequeststatechange' that is emitted currently.

**Comment by naomiaro** [comment]
You can view an example [here](http://naomiaro.github.io/waveform-playlist/loading.html)

The README has been updated as well.
