### ISSUE TITLE
Uncaught (in promise) Error: Unsupported file type

### ISSUE THREAD

**Issue by chrisbraddock** [naomiaro/waveform-playlist#80]
Hey - I ran in to an uncaught issue where someone has sent me a WMA file I've tried to throw through waveform-playlist:

![Imgur](https://i.imgur.com/AoGad9J.png)

You can see the issue by dragging any unsupported file (e.g. a .txt file even works) in your [Working With Local Files](http://naomiaro.github.io/waveform-playlist/newtracks.html) example.

I was able to catch it by throwing a `.catch` in Playlist.js at `ee.on('newtrack'...` after [this.load](https://github.com/naomiaro/waveform-playlist/blob/master/src/Playlist.js#L272) but I'm not sure what the right behavior would really be here.

If you can provide some direction I can attempt a pull request.

Any thoughts?

**Comment by naomiaro** [comment]
Hey thanks for this! This was probably always an issue, but I think just recently there was changes to how unhandled errors in promises were dealt with in browsers. I'm not quite sure of the best way to handle this right now, I'll have to check it out.

It could work to just silently catch the error and then not continue with that file, but there should be a way really if someone is using the `ee` themselves that they can get access to any errors that occurred here due to file type.

**Comment by chrisbraddock** [comment]
Thanks for the quick response. I definitely vote for exposing the error. 👍
