### ISSUE TITLE
How to Download

### ISSUE THREAD

**Issue by bradennapier** [naomiaro/waveform-playlist#9]
How do you download the finished track?

**Comment by naomiaro** [comment]
I haven't implemented a way to do this yet, it would require some code addition.

**Comment by Willena** [comment]
I have read somewhere that with web audio it is impossible to download on the fly the finished track. Each web audio output node has to be connected to something that record audio in real time, just like the microphone, but instead of connecting the microphone, you connect the output node. Here maybe each track should be passed throught web audio chanel merger to get one general output and then recorded.

This is my thinking about that but maybe there is another solution ?

**Comment by naomiaro** [comment]
There is now a released version of the library with an example to show how to export to WAV

http://naomiaro.github.io/waveform-playlist/web-audio-editor.html

Click the top blue button on the right, and a download link will appear to the right of the button!
